---
title: A simplified dynamic bioenergetic model for coral-*Symbiodinium* symbioses
author:
  - name: Ross Cunning
    email: ross.cunning@gmail.com
    affiliation: University of Hawaii
    footnote: Corresponding Author
  - name: Erik B. Muller
    affiliation: University of California
  - name: Ruth D. Gates
    affiliation: University of Hawaii
  - name: Roger M. Nisbet
    affiliation: University of California
address:
  - code: University of Hawaii
    address: Hawaii Institute of Marine Biology, Kaneohe, HI 96744, USA
  - code: University of California
    address: Department of Ecology, Evolution, and Marine Biology, Santa Barbara, CA 93106, USA
abstract: |
  This is the abstract.

bibliography: ~/library.bib
output: 
  rticles::elsevier_article:
    fig_caption: yes
header-includes:
  - \usepackage{tabularx}
---

# Introduction

The nutritional exchange between corals and *Symbiodinium* directly underlies the capacity of corals to build coral reef ecosystems, worth trillions of US Dollars annually [@Costanza:2014ex]. However, the complex symbiotic metabolism of corals is vulnerable to disruption by numerous anthropogenic environmental perturbations, jeopardizing their future persistence. In order to understand and predict coral responses to complex changes in the environment, a mechanistic understanding of how multiple interacting factors drive the individual and emergent physiology of both symbiotic partners is necessary. Such a task is well suited for theoretical modeling frameworks such as Dynamic Energy Budget (DEB) theory [@Kooijman:2010vd], although the complexity of such theory makes these efforts inaccessible to many biologists [@Jager:2013bj]. In order to bridge this gap, we present here a simplified dynamic bioenergetic model for coral-*Symbiodinium* symbioses that aims to mechanistically integrate the impacts of complex environmental change on the physiological ecology of reef corals.

In reef coral symbioses, intracellular *Symbiodinium* translocate photosynthetically-fixed carbon to support coral metabolism, and utilize the animal’s metabolic waste products, including nitrogenous compounds and carbon dioxide, in return [@Muscatine:1977p4220]. Previous application of DEB theory to this syntrophic system [@Muller:2009io] demonstrated a stable symbiotic relationship and qualitatively realistic growth and biomass ratios across gradients of ambient irradiance, nutrients, and food. This model assumed that 1) *Symbiodinium* has priority access to carbon through photosynthesis, 2) the coral animal has priority access to dissolved nitrogen through contact with seawater, and 3) each partner shares with the other only what it cannot use itself. In its simplest form, this principle of sharing the surplus sufficiently describes diverse syntrophic interactions among organs and organisms (e.g., trees, duckweeds, corals), suggesting the mechanism is mathematically and evolutionarily robust (Nisbet et al., submitted).

While the work of @Muller:2009io applying DEB formalism to this system represents the most significant theoretical contribution in coral symbiosis research to date, we aim to strengthen the role of theory and broaden its potential application to corals in three primary ways:

1. _Develop a detailed module of environmental stress._ Of primary interest to coral biologists and ecologists is symbiosis dysfunction under environmental stress, resulting in coral “bleaching”--the loss of algal symbionts from the association [@Jokiel:1977p7353]. Photooxidative stress in *Symbiodinium* is considered a primary trigger of bleaching in response to high temperature and/or light [@Weis:2008p944], and prolonged or severe bleaching can result in mortality, though corals sometimes recover their symbionts. Bleaching susceptibility, severity, and recovery may by influenced by interacting factors such as heterotrophy and nutrient availability [@Wooldridge:2014hc], and the genetic identity of *Symbiodinium* [@Glynn:2001p7571]. To simulate these bleaching-related phenomena, we develop a generalized framework linking overreduction of the photosynthetic light reactions to downstream impacts of photoinhibition and photodamage.

2. _Reduce theoretical and mathematical complexity._ Following the logic of @Jager:2013bj, we exclude certain features of formal DEB models in order to capture behaviors of interest with the simplest possible formulation. Here, we present a model without reserves, maturity, or reproduction [see @Kooijman:2010vd]. This formulation restricts the model's scope to the bioenergetics of growth and symbiosis dynamics in adult corals, but greatly reduces theoretical complexity and parameter numbers, which is advantageous given the relative paucity of data for corals. However, our primary motivation for reducing complexity was to increase accessibility and applicability for biologists and ecologists without requiring significant expertise in DEB theory.

3. _Provide well-documented, open-access code._ In order to facilitate the continued development and application of theoretical modeling tools for coral symbioses, we provide open access to the model in the form of detailed, commented code written in the R language [@RALanguageandEn:2014wf]. With an accessible and modular framework, we envision this as a resource for futher development by the scientific community to include additional complexity and problem-specific components. The R language was chosen because it is freely available and in common use by biologists and ecologists, to widen the audience for this work.

With these as our primary motivations, we describe a simplified approach to dynamic bioenergetic modeling of coral-algal symbioses that tracks carbon and nitrogen acquisition and sharing between partners. This theoretical framework dynamically integrates the influence of external irradiance, nutrients, and prey availability on coral growth and symbiosis dynamics (i.e., symbiont:host biomass ratios), allowing for the possibility of coral bleaching in the event of photooxidative stress. In the following sections, we describe the formulation of this model and justify its structure and parameter values based on relevant literature. We then demonstrate the model's behavior and discuss some of its major implications and outcomes, and the wide range of potential applications for this model in the study of cnidarian-algal symbioses.

# Model description
In this model of coral-algal symbiosis, carbon and nitrogen are acquired by each partner and used to construct biomass. A graphical representation of the model is presented in Fig. 1. We use C-moles as the unit of biomass for consistency with the rigorous mass balance of DEB theory: 1 C-mole is equivalent to the amount of biomass containing 1 mole of Carbon atoms. Host biomass ($H$), symbiont biomass ($S$), and prey biomass ($X$) have fixed, but different, molar N:C ratios (Table 1). Carbon and nitrogen are combined to produce biomass by synthesizing units (SU), which are mathematical specifications of the formation of a product from two substrates; we use the "parallel complementary" formulation of @Kooijman:2010vd to specify these fluxes. The two state variables in this dynamical system are symbiont biomass and coral biomass; because resources are acquired proportionally to surface area (and surface area is assumed proportional to volume for corals (i.e., they are "V1-morphs" in DEB terminology [@Kooijman:2010vd])), biomass increases exponentially during growth. The rate of increase in coral biomass (i.e. growth) and the ratio of symbiont to host biomass are the (i.e. symbiosis dynamics) are the responses of interest of the system. Below we describe the formulation of each flux involved in producing these responses.

Table 1

| Symbol  | Description                            | Value  | Units              |
| ------- | -------------------------------------- | ------ | ------------------ |
| $n_{NH}$ | N:C molar ratio in host biomass | 0.19 | -- |
| $n_{NS}$ | N:C molar ratio in symbiont biomass | 0.2 | -- |
| $n_{NX}$ | N:C molar ratio in prey biomass | 0.13 | -- |
| $j_{HT}^0$ | Specific turnover rate of host biomass | 0.03 | $d^{-1}$ |
| $j_{ST}^0$ | Specific turnover rate of symbiont biomass | 0.03 | $d^{-1}$ |
| $\sigma_{NH}$ | Proportion host nitrogen turnover recycled | 0.9 | -- |
| $\sigma_{CH}$ | Proportion host carbon turnover recycled | 0.9 | -- |
| $\sigma_{NS}$ | Proportion symbiont nitrogen turnover recycled | 0.9 | -- |
| $\sigma_{CS}$ | Proportion symbiont carbon turnover recycled | 0.9 | -- |
| $j_{Xm}$ | Maximum specific feeding rate of host | 0.1292 | $molX \cdot CmolH^{-1} \cdot d^{-1}$ |
| $K_X$ | Half-saturation constant for prey uptake by host | 20e-6 | $molX \cdot L^{-1}$ | 
| $j_{Nm}$ | Maximum specific DIN uptake rate by host | 0.048 | $molN \cdot CmolH^{-1} \cdot d^{-1}$ |
| $K_N$ | Half-saturation constant for DIN uptake by host | 0.46e-6 | $molN \cdot L^{-1}$ | 
| $j_{CO_2}^p$ | Passive CO~2~ delivery to symbiont | 4.04e-3 | $molC \cdot CmolH^{-1} \cdot d^{-1}$ |
| $j_{CO_2}^a$ | Active CO~2~ delivery to symbiont | 0.32--18.0 | $molC \cdot CmolH^{-1} \cdot d^{-1}$ |
| $j_{HGm}$ | Maximum specific growth rate of host | 1 | $d^{-1}$ |
| $n_{LC}$ | Quantum yield of photosynthesis | 0.1 | $molC \cdot mol ph^{-1}$ |
| $\bar{a}^*$ | Effective light-absorbing cross-section of symbiont | 1.34 | $m^2 \cdot CmolS^{-1}$ |
| $j_{NPQ}$ | Non-photochemical quenching capacity of symbiont | 40 | $mol ph \cdot CmolS^{-1} \cdot d^{-1}$|
| $k_{ROS}$ | Excess photon energy that doubles ROS prod. | 40-80 | $mol ph \cdot CmolS^{-1} \cdot d^{-1}$|
| $k$ | Exponent on ROS production rate | 1 | -- |
| $j_{CPm}$ | Maximum specific photosynthesis rate of symbiont | 2.8 | $molC \cdot CmolS^{-1} \cdot d^{-1}$ |
| $j_{SGm}$ | Maximum specific growth rate of symbiont | 0.25 | $d^{-1}$ |

Also include tables of fluxes and environmental inputs?


```{r Fig1, fig.width=5, fig.height=5, echo=FALSE, fig.cap="Graphical representation of coral-algal symbiosis model."}
library(png)
library(grid)
img <- readPNG("../img/model.png")
grid.raster(img)
```

## Coral animal fluxes

The coral animal acquires both carbon and nitrogen from feeding on prey from the environment. Prey acquisition is specified by Michaelis-Menten kinetics using a maximum area-specific feeding rate and half-saturation constant:

\begin{equation} j_X = {{j_{Xm} \cdot X} \over {X + K_X}} \end{equation}

Additionally, the coral animal can acquire nitrogen from the surrounding seawater. This nitrogen source is assumed to represent ammonium, the primary form utilized by corals [@Wang:1998p128; @Yellowlees:2008p331]. The uptake of nitrogen from the environment is specified by Michaelis-Menten kinetics using a maximum area-specific uptake rate and half-saturation constant:

\begin{equation} j_N = {{j_{Nm} \cdot N} \over {N + K_N}} \end{equation}

Coral biomass formation is specified by a parallel complementary SU that combines carbon and nitrogen to form biomass. In addition to the carbon and nitrogen acquired by direct uptake (Eqs. 1 and 2), the coral recycles a portion of the nitrogen liberated by biomass turnover ($r_{NH}=\sigma_{NH}j_{HT}^0$), and receives surplus fixed carbon shared by the symbiont ($\rho_C$), such that the total biomass formation is specified as:

\begin{equation} j_{HG} = \bigg({1 \over j_{HGm}} + {1 \over {\rho_C{S \over H} + j_X}} + {1 \over {(j_N + n_{NX}j_X + r_{NH}) / n_{NH}}} - {1 \over {{\rho_C{S \over H} + j_X} + (j_N + n_{NX}j_X + r_{NH}) / n_{NH}}}\bigg)^{-1} \end{equation}

where $j_{HGm}$ is the maximum specific growth rate. Finally, the rate of change in coral biomass is calculated as the specific growth rate minum the specific biomass turnover rate (i.e., maintenance costs), according to: 

\begin{equation} {dH \over dt} = j_{HG} - j_{HT}^0 \end{equation}

The amount of nitrogen input to the coral biomass SU in excess of what is actually consumed in biomass formation (i.e., surplus nitrogen, or the "rejection flux" in SU terminology) is then made available to the symbiont, and is specified as:

\begin{equation} \rho_N = j_N + n_{NX}j_X + r_{NH} - n_{NH}j_{HG} \end{equation}

Due to the inherent inefficiency of the parallel complementary SU formulation, there will always be some nitrogen shared with the symbiont even when coral biomass formation is strongly nitrogen-limited. Likewise, there is always a non-zero rejection flux of carbon from the coral biomass SU, which is assumed to be lost to the environment.

## *Symbiodinium* fluxes

The symbiont produces fixed carbon through photosynthesis, a process represented here by a single SU with two substrates: light (photons) and inorganic carbon (CO~2~). The amount of light absorbed by the symbiont depends on the scalar irradiance at the site of light absorption, which is modified substantially relative to external downwelling irradiance owing to multiple scattering by the coral skeleton and self-shading by surrounding symbionts [@Enriquez:2005p142; @Marcelino:2013hz]. We used data from @Marcelino:2013hz to empirically derive the ratio of internal scalar irradiance to external downwelling irradiance as a function of symbiont density (expressed as symbiont to host biomass ratio), and subsequently multiply this quantity by the external downwelling irradiance $L$ and the effective light-absorbing surface area of symbiont biomass $ds$ to specify the amount of light absorbed:

\begin{equation} j_L = \big[1.26 + 1.39 \cdot \exp(-6.48 \cdot {S \over H})\big] \cdot L \cdot \bar{a}^* \end{equation}

We then specify two pathways for input of inorganic carbon to the photosynthesis SU: 1) passive diffusion of CO~2~ from the external environment, and 2) active delivery of CO~2~ to the symbiont by the host. The passive flux ensures that some CO~2~ is always available to photosynthesis, and the active flux encompasses the potentially diverse mechanisms by which the host may enhance CO~2~ availability for the symbiont, including active transport of bicarbonate, carbonic anhydrase-catalyzed conversion of bicarbonate to CO~2~ to promote diffusion toward the symbiont, and acidification of the symbiosome to increase localized CO~2~ concentrations. Since the host physically separates the symbiont from the external environment, both the passive and active flux rates are proportional to host surface area. A more rigorous, mechanistic model of inorganic carbon processing would require spatially explicit internal pools accounting for pH and carbon speciation, which is beyond the current scope of this work. Instead, the specification of CO~2~ delivery rates offers the user the opportunity to compare different rates of CO~2~ delivery that may characterize different coral species [@Wooldridge:2014di]. The input of CO~2~ to the photosynthesis SU is therefore specified as:

\begin{equation} j_{CO_2} = j_{CO_2}^p + j_{CO_2}^a \end{equation}

In addition to the inputs CO~2~ specified in Eqs. 7, additional CO~2~ representing the metabolic production of CO~2~ from host and symbiont biomass turnover ($r_{CH}=\sigma_{CH}j_{HT}^0; r_{CS}=\sigma_{CS}j_{ST}^0$) is made available to the photosynthesis SU. fixed carbon is produced by the photosynthesis SU according to:

\begin{equation} j_{CP} = \bigg({1 \over j_{CPm}} + {1 \over {n_{LC} j_L }} + {1 \over {(j_{CO_2} + r_{CH}){H \over S} + r_{CS}}} - {1 \over {n_{LC} j_L + (j_{CO_2} + r_{CH}){H \over S} + r_{CS}}}\bigg)^{-1} \div c_{ROS} \end{equation}

where $j_{CPm}$ is the maximum specific rate of photosynthesis, and $c_{ROS}$ is the photooxidative stress multiplier (see below). Dividing by $c_{ROS}$ causes the rate of photosynthesis to decline in response to photo-oxidative stress, a phenomenon known as photoinhibition.

Light energy absorbed in excess of what is used to fix carbon is specified by the SU "rejection flux", according to:

\begin{equation} j_{eL} = j_L - j_{CP} / n_{LC} \end{equation}

This excess light energy must be quenched by alternative pathways in order to prevent photo-oxidative damage. *Symbiodinium* may utilize a variety of pathways for non-photochemical quenching [NPQ; @Roth:2014wf], which we collect in a total capacity for NPQ as a parameter of the symbiont ($j_{NPQ}$). If light energy exceeds the total capacity of both carbon fixation and NPQ, then damaging reactive oxygen species (ROS) may be produced. We represent this as a scaled flux of ROS $c_{ROS}$, which takes a value of 1 when all light absorbed is quenched by photochemistry and NPQ, and increases as the amount of excess excitation energy increases. 

\begin{equation} c_{ROS} = 1 + \bigg[\bigg({{j_{eL} - j_{NPQ}} \over k_{ROS}}\bigg)^k\bigg]_+ \end{equation}

where $j_{NPQ}$, $k_{ROS}$, and $k$ are parameters of the symbiont that determine the onset and rate of ROS production. Importantly, $c_{ROS}$ as specified here is not a function of absolute light absorption, but rather the amount of excess light energy $j_{eL}$ after accounting for carbon fixation and NPQ. A direct consequence of this formulation is that carbon-limitation of photosynthesis can lead to photo-oxidative stress, a mechanism of biological importance [@Wooldridge:2009p7807] that was not captured by previous representations of photo-oxidative stress [@Eynaud:2011tv]. Moreover, this formulation allows functional diversity among symbiont types to be explored by changing the parameters $j_{NPQ}$, $k_{ROS}$, and $k$.

Carbon fixed by photosynthesis ($j_{CP}$) is then used in conjunction with nitrogen shared by the host ($\rho_N$) and a proportion of nitrogen recycled from symbiont biomass turnover ($r_{NS}=\sigma_{NS}j_{ST}^0$) to build new symbiont biomass, following the SU equation:

\begin{equation} j_{SG} = \bigg({1 \over j_{SGm}} + {1 \over j_{CP}} + {1 \over {(\rho_N{H \over S} + r_{NS}) / n_{NH}}} - {1 \over {j_{CP} + (\rho_N{H \over S} + r_{NS}) / n_{NH}}}\bigg)^{-1} \end{equation}

The rejection flux of carbon from this SU represents the amount of fixed carbon produced by photosynthesis in excess of what can be used to produce symbiont biomass; this surplus $\rho_C$ is translocated to the coral host:

\begin{equation} \rho_C = j_{CP} - j_{SG} \end{equation}

The rejection flux of nitrogen from the symbiont biomass SU is lost to the environment.

Symbiont biomass turnover includes a component of constant turnover specified by the parameter $j_{ST}^0$, representing fixed maintenance costs, plus a component that scales with the magnitude of ROS production. 

\begin{equation} j_{ST} = j_{ST}^0(1 + 5 \cdot (c_{ROS}-1)) \end{equation}

This second component of symbiont biomass loss can represent both photodamage and/or symbiont expulsion (i.e., bleaching), both of which happen in response to higher levels or ROS production. The constant 5 is included to increase biomass loss in response to ROS. (Note that recycling of symbiont biomass turnover ($rNS$ and $rCS$) only occurs based on the basal maintenance related turnover (i.e., $j_{ST}^0$), and not the bleaching-related biomass loss, as this loss represents biomass being damaged or being expelled from the holobiont). Finally, the balance equation representing the change in symbiont biomass over time can be specified as the growth rate minus the turnover rate:

\begin{equation} {dS \over dt} = j_{SG} - j_{ST} \end{equation}

## Numerical analysis

The differential equations specified in 7 and 14 were solved using an implicit time-stepping method because of the implicit variables of surplus sharing. Euler method?


# Model behavior evaluation

# Discussion  -  Potential applications/utility

References {#references .unnumbered}
==========
