---
output: 
  html_document:
    mathjax: default
---
```{r setup}
source("../R/conversions.R")
```

### Parameter values

#### Host parameters

##### Maximum host growth rate (QRm)

* [Jacobson et al. 2016](dx.doi.org/10.1242/jeb.136044):
    + Parameterized coral symbiosis DEB model from [Muller et al. (2009)](dx.doi.org/10.1016/j.jtbi.2009.03.004) using a resource-limitation experiment. Maximum growth occurs when reserve density _m~E~_ approaches infinity; the growth rate then approaches the reserve turnover rate _k~E~_ (reported value: 0.28) minus the specific maintenance rate _j~D~_ (reported value: 0.03).
    + Reported value: `r 0.28 - 0.03` CmolR • CmolR^-1^ • day^-1^

##### Turnover rate (gammaR)
*This is the maintenance rate of the host, i.e., the amount of biomass turned over each day to pay maintenance costs.*

* [Jacobson et al. 2016](dx.doi.org/10.1242/jeb.136044):
    + Parameterized coral symbiosis DEB model (see above). The specific maintenance rate is analagous to the turnover rate in the current model.
    + Reported value: 0.03 CmolR • CmolR^-1^ • d^-1^

##### Recycled N (sigmaNR) and recycled C (sigmaCR)
* Biomass turnover generates nitrogen and carbon waste (ammonia and carbon dioxide) that can be recycled for use in biomass formation. Both host and symbiont have the capacity to assimilate ammonia, so N-waste generated by each partner is made available to their specific biomass formation synthesizing units. Carbon dioxide can only be used in photosynthesis, so the C-waste generated by both partners is made available to the symbiont photosynthesis synthesizing unit. 
    + Default values used: 0.9

##### Host N:C (nNR)
*The general heterotroph N:C ratio used in DEB modeling is 0.2 (Muller et al. 2009).*  

* [Horwitz et al. 2015](dx.doi.org/10.1038/srep08779):
    + Measured N:C ratio in *Anemonia viridis*, control *p*CO~2~ value reported below.
    + Reported value: 0.18083183 [inverse of C:N=5.53, see Results section]
* [Muller-Parker et al. 1994](http://hdl.handle.net/10125/2232):
    + Measured N:C ratio in *Pocillopora damicornis*
    + Reported value: 0.19230769 [inverse of C:N=5.2, see Abstract]

##### Maximum specific feeding rate (UXm)

* [Wijgerde et al. 2011](dx.doi.org/10.1242/jeb.058354)
    + Measured depletion of C and N from captured prey in *Galaxea fascicularis*, including both intracoelenteric and extracoelenteric feeding.
    + Reported value: 77.6 µg C • cm^-2^ • 6h^-1^ [sum of intra- and extracoelenteric feeding; Table 2]
    + Converted value: `r 77.6 / µg.g / gC.molC * cm2.m2 / CmolR.m2_Gfas * 4` CmolX • CmolR^-1^ • d^-1^

##### Half-saturation constant for feeding (XKX)

* [Purser et al. 2010](dx.doi.org/10.1016/j.jembe.2010.08.013)
    + Measured feeding rates of the coral *____* at different concentrations of *Artemia*
    + Reported value: ~345 *Artemia* • L^-1^
    + Converted value: `r 345 * gC.artemia / gC.molC * 10^6` µCmolX • L^-1^
    
##### Maximum host DIN uptake rate (UNm)

* [Muscatine & D'Elia 1978](dx.doi.org/10.4319/lo.1978.23.4.0725):
    + Measured ammonium uptake in *Pocillopora damicornis*
    + Reported value: 7.14 µmol NH~4~^+^-N • mg chl *a*^-1^ • h^-1^
    + Converted value: `r 7.14 * h.d * nmolchlA.cm2 * gchlA.molchlA * mg.g / nmol.mol / CmolR.m2_Spis * cm2.m2 / µmol.mol` mol NH~4~^+^-N • CmolR^-1^ • d^-1^
    
* [Hoegh-Guldberg & Williamson 1999](dx.doi.org/10.1007/s002270050496):
    + Measured ammonium and dissolved free amino acid uptake in *Pocillopora damicornis*
    + Reported value: 91.8 nmol N • cm^-2^ • h^-1^
    + Converted value: `r 91.8 * h.d * cm2.m2 / CmolR.m2_Spis / nmol.mol` mol N • CmolR^-1^ • d
    
* [Godinot et al. 2011 PLoS ONE](dx.doi.org/10.1371/journal.pone.0025024):
    + Measured nitrate and ammonium uptake rates in *Stylophora pistillata* under high nutrient concentrations
    + Reported value: 3.5 µmol N • mg chl^-1^ • d^-1^ [addition of bars in Fig. 4D,E @ 29°C]
    + Converted value: `r 3.5 * h.d * 22 / CmolR.m2_Spis * cm2.m2 / µmol.mol / 1000` mol N • CmolR^-1^ • d^-1^
    
* [Godinot et al. 2011 JEB](dx.doi.org/10.1242/jeb.054239):
    + Measured nitrate and ammonium uptake kinetics in *Stylophora pistillata*
    + Estimated V~max~ and K~1/2~ for each nutrient
    + Reported value (V~max~): 5.42 mol N • mg chl^-1^ • h^-1^
    + Converted value: `r 5.42 * h.d * µgchl.cm2_Spis / CmolR.m2_Spis * cm2.m2 / µmol.mol / 1000` mol N • CmolR^-1^ • d^-1^

    
##### Half-saturation constant for DIN uptake

* [Godinot et al. 2011 JEB](dx.doi.org/10.1242/jeb.054239):
    + Measured nitrate and ammonium uptake kinetics in *Stylophora pistillata*
    + Reported value (K~1/2~): 0.46 µmol • L^-1^
    
##### Host carbon concentrating for photosynthesis
*This is the amount of carbon the host takes up from the environment and makes available to symbiont photosynthesis. We assume that host delivery of DIC is the limiting step, rather than symbiont DIC uptake, because inhibiting carbonic anhydrases on the coral surface decreases symbiont photosynthesis (Tansik et al. 2015).*

* [Tansik et al. 2015](dx.doi.org/10.1007/s00338-015-1289-8):
    + Measured external carbonic anhydrase activity to estimate the amount of CO2 generated at the surface of the colony, which could then enter by diffusion and ultimately support symbiont photosynthesis.
    + Reported values: 5e-6 -- 3e-4 mol CO~2~ • cm^-2^ • h^-1^  
    + Converted values: `r 5e-6 * h.d * cm2.m2 / CmolR.m2` -- `r 3e-4 * h.d * cm2.m2 / CmolR.m2` mol CO~2~ • CmolR^-1^ • d^-1^
    + Lower value used in case downstream steps may further limit DIC available to photosynthesis.
    + In the absence of eCA, a maximum rate of passive CO~2~ influx was estimated:
        + 6.4e-8 CO~2~ • cm^-2^ • h^-1^
        + Converted value: `r 6.4e-8 * h.d * cm2.m2 / CmolR.m2` mol CO~2~ • CmolR^-1^ • d^-1^

#### Symbiont parameters

##### Maximum symbiont growth rate

* [Sugget et al. 2015](10.1111/nph.13483):
    + Measured growth rates of 18 *Symbiodinium* types in culture across 5 clades using FRR fluorometry.
    + Reported values: 0.19-0.26 day^-1^
* Change et al. 2983
    + Measured specific growth rates of *Symbiodinium* in culture based on cell counting at different growth irradiances.
    + Reported values: 0.22 -- 0.43 day^-1^ [Table 9]

##### Symbiont biomass turnover rate

* This value is set to equal the turnover rate for the host: 0.03 day^-1^

##### Recycled N and recycled C

* Biomass turnover generates nitrogen and carbon waste (ammonia and carbon dioxide) that can be recycled for use in biomass formation. Both host and symbiont have the capacity to assimilate ammonia, so N-waste generated by each partner is made available to their specific biomass formation synthesizing units. Carbon dioxide can only be used in photosynthesis, so the C-waste generated by both partners is made available to the symbiont photosynthesis synthesizing unit. 
    + Default values used: 0.9
    
##### Symbiont biomass N:C ratio (nNS)

*Theoretically should be close to Redfield ratio at 0.15.*  

* [Horwitz et al. 2015](dx.doi.org/10.1038/srep08779):
    + Measured N:C ratio in *Symbiodinium* from *Anemonia viridis*.
    + Reported value: 0.137 [inverse of C:N in Fig. 5]
* [Muscatine et al. 1989](dx.doi.org/10.1098/rspb.1989.0025):
    + Reported value: 0.12987013 [inverse of C:N=7.7 in Table 2]

##### Maximum symbiont photosynthetic rate (UCSm)
*In theory, this is the maximum carboxylation rate of* Symbiodinium *Rubisco (RuBP).*

* [Leggat et al. 2004](https://digitalcollections.anu.edu.au/handle/1885/87271):
    + Estimated RuBP carboxylation at 29°C.
    + Reported value: 140 CO~2~ • RuBP^-1^ • s^-1^ [Max. value, p. 143]
    + Converted value: `r 140 * s.h * h.d * RuBP.CmolS` mol CO~2~ • CmolS^-1^ • d^-1^

*Other maximum photosynthesis rates from literature:*

* [Oakley et al. 2014](dx.doi.org/10.1007/s00338-014-1130-9):
    + Measured light- and DIC-saturated rates of O~2~ evolution in various types of cultured *Symbiodinium*
    + Reported values: 6.11 - 21.85 nmol O~2~ • mm^-3^ • min^-1^ [Fig. 2C; note: incorrect units reported in publication, corrected data and units obtained from C. Oakley]
    + Converted values: `r 6.11 * min.d / nmol.mol * mm3.µm3 / CmolS.µm3` - `r 21.85 * min.d / nmol.mol * mm3.µm3 / CmolS.µm3` mol O~2~ • CmolS^-1^ • d^-1^

* [Brading et al. 2013](dx.doi.org/10.1111/nph.12379):
    + Measured light- and DIC-saturated C-fixation in cultured *Symbiodinium* A13
    + Reported value: 259 mmol C • g chl *a*^-1^ • h^-1^ [from Table 4]
    + Converted value: `r 259 * gchlA.CmolS * h.d / mmol.mol` mol C • CmolS^-1^ • d^-1^
    
* Tansik unpublished:
    + Ofav Pmax: 9.94e-7 mol O~2~ • cm^-2^ • h^-1^
    + Converted: `r 9.94e-7 * h.d * cm2.m2 / CmolR.m2 / 0.1` mol O~2~ • CmolS^-1^ • d^-1^
    + Sym B1 Pmax: 2.69e-17 mol O2 • cell^-1^ • s^-1^
    + Converted: `r 2.69e-17 * s.h * h.d / pgC.cellS * pg.g * gC.molC` mol O~2~ • CmolS^-1^ • d^-1^
    + Past Pmax: 1.82e-6 mol O~2~ • cm^-2^ • h^-1^
    + Converted: `r 1.82e-6 * h.d * cm2.m2 / CmolR.m2 / 0.1` mol O~2~ • CmolS^-1^ • d^-1^
    + Sym A4a Pmax: 7.18e-17 mol O2 • cell^-1^ • s^-1^
    + Converted: `r 7.18e-17 * s.h * h.d / pgC.cellS * pg.g * gC.molC` mol O~2~ • CmolS^-1^ • d^-1^
    + Srad Pmax: 1.26e-6 mol O~2~ • cm^-2^ • h^-1^
    + Converted: `r 1.26e-6 * h.d * cm2.m2 / CmolR.m2 / 0.1` mol O~2~ • CmolS^-1^ • d^-1^
    + Sym B5 Pmax: 6.08e-17 mol O2 • cell^-1^ • s^-1^
    + Converted: `r 6.08e-17 * s.h * h.d / pgC.cellS * pg.g * gC.molC` mol O~2~ • CmolS^-1^ • d^-1^
    
##### Symbiont light absorption cross section (ds)
*The effective light-absorbing surface area of symbiont biomass.*

* [Hennige et al. 2009](dx.doi.org/10.1007/s00338-008-0444-x):
    + Measured spectra-weighted absoprtion coefficients from 400 to 700nm *ā\**~(400-700)~ of eight *Symbiodinium* types in culture at two different light levels (grand mean reported here).
    + Reported value: 0.01095 m^2^ • mg chl *a*^-1^ [from Table 6]
    + Converted value: `r 0.01095 * mg.g * gchlA.gC * gC.molC` m^2^ • CmolS^-1^

##### Quantum efficiency
*The number of O~2~ molecules evolved (or C fixed) per photon absorbed. The maximum theoretical value is 0.125.*

* [Brodersen et al. 2014](dx.doi.org/10.1098/rsif.2013.0997):
    + Present balanced light budget based on microenvironmental photobiology of *Montastrea curta*.
    + Reported value: 0.102 O~2~ photon^-1^
    
##### L50
*The amount of excitation energy in excess of both photochemical and non-photochemical quenching (NPQ) that leads to a doubling in ROS production relative to baseline values.* Units: mol photons • CmolS^-1^ • d^-1^. Values used here were determined by matching the "bleaching" response of the model to observed values of irradiance where this response is expected to occur (i.e., 40-60 mol photons • m^-2^ • d^-1^). 

##### NPQ
*The flux of excitation energy in excess of photochemical quenching that can be quenched non-photochemically without producing ROS. This can be conceptually considered as the capacity for non-photochemical quenching (NPQ) in the symbiont.* Units: mol photons • CmolS^-1^ • d^-1^.

* [Gorbunov et al. 2001](dx.doi.org/10.4319/lo.2001.46.1.0075):
    + Measured the daily integrated amount of photons quenched by both photosynthetic electron transport and non-photochemical quenching (=thermal dissipation, or NPQ) in _Montastraea faveolata_ on a sunny day.
    + Reported NPQ value: 15.3 mol _e_ • m^-2^ • d^-1^.
    + Assume ~10% of total biomass is symbiont
    + Calculated value: `r 15.3 / CmolR.m2 / 0.1` mol photons • CmolS^-1^ • d^-1^

##### k
*The exponent determining the rate of increase in ROS production as a function of excess excitation energy.* Dimensionless. A default value of 1 is used here such that ROS production scales linearly with excess excitation energy. 
