---
title: "TestFigS9"
author: "Ross Cunning, Erik B. Muller, Ruth D. Gates, Roger M. Nisbet"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 1
bibliography: library.bib
---


```{r setup, include=FALSE}
require(pander)
require(stringr)
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::opts_chunk$set(message = F, warning = F, echo=T, results='asis')
knitr::opts_chunk$set(results = "asis", render=pander)
```

```{r initialize, include=FALSE}
# Source default parameters and functions
sapply(c("R/conversions.R", "R/def_pars.R", "R/init_env.R", "R/plot_results.R",
         "R/run_coral.R", "R/run_coral_ss.R", "R/sym_PI.R", "R/run_steady_states.R", 
         "R/plot_steady_states.R", "R/sensitivity.R"), source, .GlobalEnv)
# Get default parameters
defpars <- def_pars()
```


# Figure S9
```{r FigS9}

# Set up cluster for parallel processing
cl <- makeCluster(detectCores())  # Initiate cluster
registerDoParallel(cl)

# Set input values for steady state runs
input <- expand.grid(L=seq(59,60,1), initS=c(0.0001,0.1))

# Run steady states in parallel
output1 <- foreach(i=1:nrow(input), .combine=rbind) %dopar% {
  run <- run_coral_ss(env=list(L=input$L[i], X=2e-6, N=1e-7), pars=replace(defpars, "initS", input$initS[i]), dt=0.1)
  list(gr=last(run$H$dH.Hdt), sh=last(run$S$S/run$H$H))
}

output2 <- foreach(i=1:nrow(input), .combine=rbind) %dopar% {
  run <- run_coral_ss(env=list(L=input$L[i], X=1e-6, N=1e-7), pars=replace(defpars, "initS", input$initS[i]), dt=0.1)
  list(gr=last(run$H$dH.Hdt), sh=last(run$S$S/run$H$H))
}

output3 <- foreach(i=1:nrow(input), .combine=rbind) %dopar% {
  run <- run_coral_ss(env=list(L=input$L[i], X=2e-6, N=1e-6), pars=replace(defpars, "initS", input$initS[i]), dt=0.1)
  list(gr=last(run$H$dH.Hdt), sh=last(run$S$S/run$H$H))
}

output4 <- foreach(i=1:nrow(input), .combine=rbind) %dopar% {
  run <- run_coral_ss(env=list(L=input$L[i], X=4e-6, N=1e-6), pars=replace(defpars, "initS", input$initS[i]), dt=0.1)
  list(gr=last(run$H$dH.Hdt), sh=last(run$S$S/run$H$H))
}

stopCluster(cl)  # Stop cluster

# Collect results
res1 <- cbind(input, output1)
res2 <- cbind(input, output2)
res3 <- cbind(input, output3)
res4 <- cbind(input, output4)


# Create plot
par(mfrow=c(2,2), mar=c(3,3,1,1), mgp=c(1.5,0.5,0), tcl=-0.025)

plot(NA, xlim=range(input$L), ylim=c(0,0.5), xlab="Light", ylab="Steady state S:H ratio")
title("DIN=1e-7 mol/L; X=2e-6 mol/L")
points(c(48,48,53,53), c(0.42,0.45,0.42,0.45), pch=c(19,1,19,1), cex=c(0.4,1,0.4,1), col=c("black","black","red","red"), xpd=T)
text(38, 0.435, labels="init. S:H", xpd=T, cex=0.7, srt=90)
text(46, c(0.42,0.45), labels=c("0.1", "0.0001"), xpd=T, pos=2, cex=0.7)
text(50, 0.49, labels=c("Steady state growth"), xpd=T, cex=0.7)
text(c(48,53), 0.47, labels=c("pos.", "neg."), xpd=T, cex=0.7)
apply(res1, 1, FUN=function(x) {
  with(x, points(L, sh,
                 col=ifelse(gr>0, "black", "red"), 
                 pch=ifelse(initS==1e-01, 19, 1), 
                 cex=ifelse(initS==1e-01, 0.4, 1)))
  with(x, if (sh > 0.5) {
    points(L, 0.5, pch="^", 
           col=ifelse(gr>0, "black", "red"))
    points(L, 0.49, 
           col=ifelse(gr>0, "black", "red"),
           pch=ifelse(initS==1e-01, 19, 1), 
           cex=ifelse(initS==1e-01, 0.4, 1))
  })
})

plot(NA, xlim=range(input$L), ylim=c(0,0.5), xlab="Light", ylab="Steady state S:H ratio")
title("DIN=1e-7 mol/L; X=1e-6 mol/L")
apply(res2, 1, FUN=function(x) {
  with(x, points(L, sh,
                 col=ifelse(gr>0, "black", "red"), 
                 pch=ifelse(initS==1e-01, 19, 1), 
                 cex=ifelse(initS==1e-01, 0.4, 1)))
  with(x, if (sh > 0.5) {
    points(L, 0.5, pch="^", 
           col=ifelse(gr>0, "black", "red"))
    points(L, 0.49, 
           col=ifelse(gr>0, "black", "red"),
           pch=ifelse(initS==1e-01, 19, 1), 
           cex=ifelse(initS==1e-01, 0.4, 1))
  })
})

plot(NA, xlim=range(input$L), ylim=c(0,0.5), xlab="Light", ylab="Steady state S:H ratio")
title("DIN=1e-6 mol/L; X=2e-6 mol/L")
apply(res3, 1, FUN=function(x) {
  with(x, points(L, sh,
                 col=ifelse(gr>0, "black", "red"), 
                 pch=ifelse(initS==1e-01, 19, 1), 
                 cex=ifelse(initS==1e-01, 0.4, 1)))
  with(x, if (sh > 0.5) {
    points(L, 0.5, pch="^", 
           col=ifelse(gr>0, "black", "red"))
    points(L, 0.49, 
           col=ifelse(gr>0, "black", "red"),
           pch=ifelse(initS==1e-01, 19, 1), 
           cex=ifelse(initS==1e-01, 0.4, 1))
  })
})

plot(NA, xlim=range(input$L), ylim=c(0,0.5), xlab="Light", ylab="Steady state S:H ratio")
title("DIN=1e-6 mol/L; X=4e-6 mol/L")
apply(res4, 1, FUN=function(x) {
  with(x, points(L, sh,
                 col=ifelse(gr>0, "black", "red"), 
                 pch=ifelse(initS==1e-01, 19, 1), 
                 cex=ifelse(initS==1e-01, 0.4, 1)))
  with(x, if (sh > 0.5) {
    points(L, 0.5, pch="^", 
           col=ifelse(gr>0, "black", "red"))
    points(L, 0.49, 
           col=ifelse(gr>0, "black", "red"),
           pch=ifelse(initS==1e-01, 19, 1), 
           cex=ifelse(initS==1e-01, 0.4, 1))
  })
})

```
